SET SOURCE_DIR="C:\Data\Projects\strawberry\strawberry"
SET BUILD_DIR="C:\Data\Projects\strawberry\strawberry\out\build\x64-Release"

SET BIN_DIR="C:\strawberry_msvc_x86_64_release\bin"
SET QT_DIR="C:\strawberry_msvc_x86_64_release"
SET GIO_DIR="C:\strawberry_msvc_x86_64_release\lib\gio\modules"
SET GST_DIR="C:\strawberry_msvc_x86_64_release\lib\gstreamer-1.0"

MKDIR "%BUILD_DIR%\platforms"
MKDIR "%BUILD_DIR%\tls"
MKDIR "%BUILD_DIR%\styles"
MKDIR "%BUILD_DIR%\sqldrivers"
MKDIR "%BUILD_DIR%\imageformats"
MKDIR "%BUILD_DIR%\gio-modules"
MKDIR "%BUILD_DIR%\gstreamer-plugins"

COPY %SOURCE_DIR%\COPYING "%BUILD_DIR%\"
COPY %SOURCE_DIR%\dist\windows\*.nsh "%BUILD_DIR%\"
COPY %SOURCE_DIR%\dist\windows\*.nsi "%BUILD_DIR%\"
COPY %SOURCE_DIR%\dist\windows\*.ico "%BUILD_DIR%\"

COPY "%BIN_DIR%\libcrypto-3-x64.dll" "%BUILD_DIR%\"
COPY "%BIN_DIR%\libssl-3-x64.dll" "%BUILD_DIR%\"

COPY "%BIN_DIR%\soup-2.4-1.dll" "%BUILD_DIR%\"
COPY "%BIN_DIR%\sqlite3.exe" "%BUILD_DIR%\"
COPY "%BIN_DIR%\gst-launch-1.0.exe" "%BUILD_DIR%\"
COPY "%BIN_DIR%\gst-discoverer-1.0.exe" "%BUILD_DIR%\"

COPY "%QT_DIR%\plugins\platforms\qwindows.dll" "%BUILD_DIR%\platforms\"
COPY "%QT_DIR%\plugins\tls\qschannelbackend.dll" "%BUILD_DIR%\tls\"
COPY "%QT_DIR%\plugins\tls\qopensslbackend.dll" "%BUILD_DIR%\tls\"
COPY "%QT_DIR%\plugins\styles\qwindowsvistastyle.dll" "%BUILD_DIR%\styles\"
COPY "%QT_DIR%\plugins\sqldrivers\qsqlite.dll" "%BUILD_DIR%\sqldrivers\"
COPY "%QT_DIR%\plugins\imageformats\qjpeg.dll" "%BUILD_DIR%\imageformats\"
COPY "%QT_DIR%\plugins\imageformats\qgif.dll" "%BUILD_DIR%\imageformats\"
COPY "%QT_DIR%\plugins\imageformats\qico.dll" "%BUILD_DIR%\imageformats\"

COPY "%GIO_DIR%\giognutls.dll" "%BUILD_DIR%\gio-modules\"
COPY "%GIO_DIR%\gioopenssl.dll" "%BUILD_DIR%\gio-modules\"

copy "%GST_DIR%\gstaes.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstaiff.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstapetag.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstapp.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstasf.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstasfmux.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstaudioconvert.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstaudiofx.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstaudiomixer.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstaudioparsers.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstaudiorate.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstaudioresample.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstaudiotestsrc.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstautodetect.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstbs2b.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstcoreelements.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstdash.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstdirectsound.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstequalizer.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstfaac.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstfaad.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstfdkaac.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstflac.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstgio.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstgme.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gsthls.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gsticydemux.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstid3demux.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstid3tag.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstisomp4.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstlame.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstlibav.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstmpg123.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstmusepack.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstogg.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstopenmpt.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstopus.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstopusparse.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstpbtypes.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstplayback.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstreplaygain.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstrtp.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstrtsp.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstsoup.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstspectrum.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstspeex.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gsttaglib.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gsttcp.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gsttwolame.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gsttypefindfunctions.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstudp.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstvolume.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstvorbis.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstwasapi.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstwavenc.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstwavpack.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstwavparse.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "%GST_DIR%\gstxingmux.dll" "%BUILD_DIR%\gstreamer-plugins\"

PAUSE
