SET QT_DIR="C:\qt\6.2.3\msvc2019_64"
SET LIB_DIR="C:\Data\Projects\strawberry\dependencies\msvc"
SET SOURCE_DIR="C:\Data\Projects\strawberry\strawberry"
SET BUILD_DIR="C:\Data\Projects\strawberry\strawberry\out\build\x64-Debug"

MKDIR "%BUILD_DIR%\platforms"
MKDIR "%BUILD_DIR%\tls"
MKDIR "%BUILD_DIR%\styles"
MKDIR "%BUILD_DIR%\sqldrivers"
MKDIR "%BUILD_DIR%\imageformats"
MKDIR "%BUILD_DIR%\gio-modules"
MKDIR "%BUILD_DIR%\gstreamer-plugins"

COPY %SOURCE_DIR%\COPYING "%BUILD_DIR%\"
COPY %SOURCE_DIR%\dist\windows\*.nsh "%BUILD_DIR%\"
COPY %SOURCE_DIR%\dist\windows\*.nsi "%BUILD_DIR%\"
COPY %SOURCE_DIR%\dist\windows\*.ico "%BUILD_DIR%\"

COPY "C:\Qt\Tools\OpenSSL\Win_x64\bin\libcrypto-1_1-x64.dll" "%BUILD_DIR%\"
COPY "C:\Qt\Tools\OpenSSL\Win_x64\bin\libssl-1_1-x64.dll" "%BUILD_DIR%\"

COPY "C:\gstreamer\1.0\msvc_x86_64\bin\soup-2.4-1.dll" "%BUILD_DIR%\"
COPY "C:\gstreamer\1.0\msvc_x86_64\bin\gst-launch-1.0.exe" "%BUILD_DIR%\"
COPY "C:\gstreamer\1.0\msvc_x86_64\bin\gst-discoverer-1.0.exe" "%BUILD_DIR%\"

COPY "%QT_DIR%\plugins\platforms\qwindowsd.dll" "%BUILD_DIR%\platforms\"
COPY "%QT_DIR%\plugins\tls\qopensslbackendd.dll" "%BUILD_DIR%\tls\"
COPY "%QT_DIR%\plugins\styles\qwindowsvistastyled.dll" "%BUILD_DIR%\styles\"
COPY "%QT_DIR%\plugins\sqldrivers\qsqlited.dll" "%BUILD_DIR%\sqldrivers\"
COPY "%QT_DIR%\plugins\imageformats\qjpegd.dll" "%BUILD_DIR%\imageformats\"
COPY "%QT_DIR%\plugins\imageformats\qgifd.dll" "%BUILD_DIR%\imageformats\"
COPY "%QT_DIR%\plugins\imageformats\qicod.dll" "%BUILD_DIR%\imageformats\"

COPY "C:\Data\Projects\strawberry\strawberry-dependencies\msvc\sources\glib-networking-2.62.4\build\tls\gnutls\giognutls.dll" "%BUILD_DIR%\gio-modules\"

copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstapp.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstcoreelements.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstaudioconvert.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstaudiofx.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstaudiomixer.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstaudioparsers.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstaudiorate.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstaudioresample.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstaudiotestsrc.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstautodetect.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstplayback.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstvolume.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstspectrum.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstequalizer.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstreplaygain.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gsttypefindfunctions.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstgio.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstdirectsound.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstwasapi.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstwasapi2.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstapetag.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gsticydemux.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstid3demux.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gsttcp.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstudp.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstsoup.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstrtp.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstrtsp.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstflac.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstwavparse.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstwavpack.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstogg.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstvorbis.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstopus.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstopusparse.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstspeex.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstlame.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstaiff.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstisomp4.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstasf.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstasfmux.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstlibav.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstdash.dll" "%BUILD_DIR%\gstreamer-plugins\"
copy "C:\gstreamer\1.0\msvc_x86_64\lib\gstreamer-1.0\gstxingmux.dll" "%BUILD_DIR%\gstreamer-plugins\"

PAUSE
